### ISSUE TITLE
proposal: Make the engine toolkit code private

### ISSUE THREAD

**Issue by matryer** [veritone/engine-toolkit#55]
Since #50 the project is no longer buildable by anybody outside of the company org (it now depends on a private repo). I suggest close-sourcing the engine toolkit project.

**Comment by jay-a-brown** [comment]
Was there any discussion about this?

**Comment by matryer** [comment]
We either need to remove that private dependency, or close this project. It cannot be built.

Note; we are using the Releases tab to share the binary. We'd need to find an alternative if we make this repo private.

**Comment by jay-a-brown** [comment]
I vote we remove the dependency for now until we have a more considered plan for this project's use by developers.
